[build]
  base = "frontend"                 # directory containing frontend package.json
  publish = "frontend/build"        # folder to serve
  command = "npm run build"         # frontend build command

[dev]
  framework = "create-react-app"
  port = 3000
